### ISSUE TITLE
where is window.addEventListener?

### ISSUE THREAD

**Issue by stefensuhat** [ng-chicago/AddToHomeScreen#1]
Hi,

I'm not seeing where you put 

```
 window.addEventListener('beforeinstallprompt', (e) => {})
```

why you can call `this.deferredPrompt.prompt();` 

Do you have any react example? I'm struggling to make this work on react project.

**Comment by ng-chicago** [comment]
It is in this typescript file: https://github.com/ng-chicago/AddToHomeScreen/blob/master/src/app/app.component.ts

**Comment by ng-chicago** [comment]
Sorry, I do not work with react, just Angular
