### ISSUE TITLE
AddToHomeScreen on Vue

### ISSUE THREAD

**Issue by mjatta** [ng-chicago/AddToHomeScreen#2]
Hi,

I'm trying to follow your example to implement add to home screen button on a Vue project but I'm having couple of issues 

My JS looks like this 
window.addEventListener('beforeinstallprompt', (e) => {    
    // show your custom button
    
    // Prevent Chrome 67 and earlier from automatically showing the prompt
    // no matter what, the snack-bar shows in 68 (beta 06/16/2018 11:05 AM)
    e.preventDefault();
    
    // Save the prompt so it can be displayed when the user wants
    this.deferredPrompt = e; 
}); 

window.addEventListener('appinstalled', (evt) => {
    // if installed, hide your custom button?
    // if installed, call Google Analytics to track?
    app.logEvent('a2hs', 'installed');
});

 if (window.matchMedia('(display-mode: standalone)').matches) {
      // do things here
      // e.g. call Google Analytics to track standalone use 
    }

On my HTML I added a 
button class="btn-a2hs" type="button">Add Shortcut To Home/Apps Screen</button>

The console does not show any errors but the button is showing at all times and that does not seems right, it should show and hide depending.

**Comment by ng-chicago** [comment]
Sorry, I am not familiar with Vue. All of my projects are Angular.
