### ISSUE TITLE
Chrome on iPhone detected as Safari

### ISSUE THREAD

**Issue by jovpet** [ng-chicago/AddToHomeScreen#3]
when I use chrome on iPhone here is the user agent object:
```
isStandalone: false
isChrome: false
...
isSafari: true
isIOS: true
isMobile: true
```

mozilla/5.0 (iphone; cpu iphone os 12_2 like mac os x)
applewebkit/605.1.15(khtml, like gecko)
crios/74.0.3729.155 mobile/15e148 safari/605.1

**Comment by ng-chicago** [comment]
Sorry, I have no iPhone, only Android

**Comment by gedw99** [comment]
I also have this same problem.

On iOS , when in Chrome , no A2HS prompt occurs . It used to but Apple seems to have changed something . 

Also the share action brings up a list of actions but none of them is to “ save to homescreen “.

the solution that I have seen used is to make your own prompt with a dialogue . I am not sure if that works anymore though . I need to try
